### ISSUE TITLE
Bot closes issues as completed despite configuration

### ISSUE THREAD

**Issue by aaronliu0130** [actions/stale#1015]
**Description:**
https://github.com/upscayl/upscayl/blob/main/.github/stale.yml clearly set the close-issue-reason to not_planned.

**Action version:**
I have no idea. However this was only installed a week ago, so I believe it’s the latest.

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
1. Install on repo with stale issues
2. Notice it closes as completed by default
3. Set close-issue-reason to not_planned
4. Notice it still closes as completed

**Expected behavior:**
Bot closes issues as not planned.

**Actual behavior:**
Bot closes issues as completed.

**Comment by dsame** [comment]
Thank you @aaronliu0130 for you input, we are starting to investigate the issue

**Comment by MAGICCC** [comment]
Seems you are using the stale bot (https://github.com/marketplace/stale) and not this action.

**Comment by aaronliu0130** [comment]
Huh, that's very confusing.

**Comment by MAGICCC** [comment]
Hm? The two projects are complete different, but I prefer using this action since the App tends to hang and do nothing over weeks
