### ISSUE TITLE
Add opposite of exempt-issue-labels

### ISSUE THREAD

**Issue by Gummibeer** [actions/stale#104]
I have the case that I want to use different settings for some labels. For example `invalid` or `duplicate` issues should get a much shorter timespan before they are stale/closed than other regular issues.

For this I would like to use a `required-issue-labels` or similar setting and have multiple jobs in my workflow.
In theory I could exclude all other labels, but requiring some would be much easier - allow-list vs deny-list.

**Comment by akulgoel96** [comment]
There is a configuration called `only-lables`.
https://github.com/actions/stale/blob/master/action.yml#L30

**Comment by Gummibeer** [comment]
@akulgoel96 Thanks! ☺️
