### ISSUE TITLE
Action continues marking PRs as stale, although it should not do it

### ISSUE THREAD

**Issue by dartcafe** [actions/stale#1071]
**Description:**
PRs get marked as stale and closed, but they should be ignored, as configured.

Example: https://github.com/nextcloud/polls/pull/2928

The action seems to recognize the exempt-labels and judging from the log, the PR is skipped, but nevertheless the stale label got added. Additionally, this PR is a draft and also should get ignored because of this.

I can't identify any misconfiguration.

**Action version:**
v8

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
See PRs here: https://github.com/nextcloud/polls/pulls
Action file: https://github.com/nextcloud/polls/blob/master/.github/workflows/stale.yml
Todays action log: https://github.com/nextcloud/polls/actions/runs/5791954264/job/15697526998

**Expected behavior:**
The PRs should not be marked as stale as defined in the action config

**Actual behavior:**
PRs without any action in the last days get marked as stale and also get closed on a regulary basis although they should  be skipped.

**Comment by dsame** [comment]
Hello @dartcafe , we will start to investigate the issue

**Comment by dsame** [comment]
Hello @dartcafe , it seems the PR is closed by another stale workflow https://github.com/nextcloud/polls/blob/master/.github/workflows/missing_template.yml

Can you please disable it and check if problem exists?

**Comment by dartcafe** [comment]
Ehm. Yes. What can I say? 🙈 
OMFG, Thanks and sorry. I really didn't see that action. Thanks a lot!!!
