### ISSUE TITLE
Multiple token option

### ISSUE THREAD

**Issue by polsala** [actions/stale#1095]
**Description:**
Enable token rotation option

**Justification:**
For big repos rate limit could be a problem, using multiple tokens from different users can solve the problem and can be processed in a single run

**Are you willing to submit a PR?**

Probably

**Comment by dsame** [comment]
Hello @polsala , the problem with big repos solved with this [PR](https://github.com/actions/stale/pull/1033) - it will become available to all users in the next release. 

Does it helps to solve the problem?

**Comment by polsala** [comment]
> Hello @polsala , the problem with big repos solved with this [PR](https://github.com/actions/stale/pull/1033) - it will become available to all users in the next release.
> 
> Does it help to solve the problem?

Good morning, yes, thank you!
