### ISSUE TITLE
Egypt.com

### ISSUE THREAD

**Issue by fetouh88** [actions/stale#1100]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by fetouh88** [comment]
shop now

**Comment by dsame** [comment]
Hello @fetouh88 , 
The issue lacks any useful information and appears to be spam. I have closed it, but please feel free to reopen it with additional information or create a new one.
