### ISSUE TITLE
Actions Marketplace is recommending v4.1.1 as the latest version

### ISSUE THREAD

**Issue by maxb** [actions/stale#1102]
The GitHub Actions Marketplace appears to be naively ordering releases by time of release, and promoting v4.1.1 as the latest version:

https://github.com/marketplace/actions/close-stale-issues

In light of this behaviour, it might be better to withdraw late patch releases for old release branches from Marketplace publication.

**Comment by dsame** [comment]
Hello @maxb , thanks for the input, we will start to investigate the issue

**Comment by crispyblock** [comment]
I thought the Tagging and Releases looked a little fishy.

Can anyone share some insight about how it is being managed? and which version they recommend?

**Comment by maxb** [comment]
Something has changed, and the releases are now sorted correctly in the Marketplace.
