### ISSUE TITLE
I

### ISSUE THREAD

**Issue by GCC1111** [actions/stale#1104]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by GCC1111** [comment]
https://github.com/actions/stale/issues/1104

**Comment by dsame** [comment]
The issue closed as a spam
