### ISSUE TITLE
Saved state not found

### ISSUE THREAD

**Issue by rcomer** [actions/stale#1124]
**Description:**
Workflow ran out of operations on the first run but still started from the beginning on the second.

**Action version:**
9

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Here is our workflow: [Label inactive PRs](https://github.com/matplotlib/matplotlib/blob/c79146493b9e5452468eae0b8d66e13c5fa5a581/.github/workflows/stale.yml).

This has run twice since updating to v9.  On the first run, the output indicated [state: persisting info about 203 issue(s)](https://github.com/matplotlib/matplotlib/actions/runs/7242568550/job/19728176986#step:2:3592).  On the next run, [The saved state was not found, the process starts from the first issue.](https://github.com/matplotlib/matplotlib/actions/runs/7269892766/job/19808179095#step:2:30)

We have `operations-per-run` set low in order to work slowly through a large backlog of issues, but didn't want steps like removing the label after update or closing the issue to wait until we'd worked through the whole backlog.  So when we updated to v9, we also added a second workflow using the action with `days-before-stale=-1` and a much higher `operations-per-run` (see my PR here https://github.com/matplotlib/matplotlib/pull/27523).  The two workflows run on alternate days.  Perhaps using the second workflow is interfering with the state somehow?  Though the state [was also not found](https://github.com/matplotlib/matplotlib/actions/runs/7256252695/job/19768252298#step:2:26) by the second workflow when it ran in between.

**Expected behavior:**
Original workflow finds state and works from where it got to last time.

**Actual behavior:**
Original workflow does not find state, starts from the beginning.

**Comment by marko-zivic-93** [comment]
Hello @rcomer 
Thank you for creating this issue. We will investigate it and come back to you as soon as we have some feedback.

**Comment by rcomer** [comment]
I tried to reproduce the problem in a [dummy repo](https://github.com/rcomer/bjl-stale/tree/main/.github/workflows) and couldn't.  Both workflows successfully interact with the cached state.  Any suggestions for troubleshooting why Matplotlib's workflows are not finding the state?

For Matplotlib's use-case we would want the second workflow to ignore the cached state that the first one saved.  Is that something that would be easy to implement?  Or is there a better way to make sure the already-labelled issues get closed or their labels removed in a timely manner?

Thanks!

**Comment by rcomer** [comment]
Actually the second workflow [*did* find the cache](https://github.com/matplotlib/matplotlib/actions/runs/7381398369/job/20079891845#step:2:28) when it ran two days ago (and then deleted it because it worked through all the remaining issues).  A new cache was then saved by the first workflow one day ago, and is still there, but [was not found by the most recent run of the second workflow](https://github.com/matplotlib/matplotlib/actions/runs/7404530170/job/20146181424#step:2:26).

So I fear that whatever is going wrong here is not reproducible ☹️

**Comment by anomiex** [comment]
Possibly this is the same as #1136?

**Comment by rcomer** [comment]
We do indeed have many caches!

**Comment by rcomer** [comment]
I'm going to close this as a duplicate of #1136 which has debugging details.  I will open a new feature request for our issue about using more than one workflow.
