### ISSUE TITLE
Stale action showing up several times in "checks"

### ISSUE THREAD

**Issue by ryanwilsonperkin** [actions/stale#13]
Hi, we've just started using this action on one of our repos and I noticed that it's reporting a "check" against our commits for everything that's in an open PR. This is resulting in some PR commits as having many such "checks" against them, is there a way to avoid this?

Here's a recent example of a PR that was open over night having ~18 "checks" against it for the stale action workflow:

![image](https://user-images.githubusercontent.com/3004111/63782486-74776f00-c8b9-11e9-9d4b-87f0ae5924db.png)

I'm concerned that this will drown out the otherwise useful checks that we're using for CI reporting on our PRs.

**Comment by gimenete** [comment]
We have shipped a fix for this. Here's a blog post with more information https://github.blog/changelog/2019-09-24-ui-changes-in-github-actions-checks/

**Comment by ajcann** [comment]
@ryanwilsonperkin  Still seeing this currently in our PRs under the scenario - 
```
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize]
```
<img width="720" alt="Screen Shot 2019-12-03 at 6 41 10 PM" src="https://user-images.githubusercontent.com/10137494/70107850-89704680-15fc-11ea-8f70-fe5c5e3cb1cb.png">

**Comment by ryanwilsonperkin** [comment]
@ajcann you may want to open a new issue linking this one and tagging their support team, I don't work at GitHub 🙂

**Comment by ajcann** [comment]
> @ajcann you may want to open a new issue linking this one and tagging their support team, I don't work at GitHub 🙂

Whoops wrong @ thanks :)

**Comment by gimenete** [comment]
@ajcann can you link me to a PR where that happens? Thanks!

**Comment by ajcann** [comment]
@gimenete  Sure thing - I created a public example repo and PR here:  https://github.com/ajcann/multiple-checks-issue/pull/2

**Comment by gimenete** [comment]
@ajcann sorry for the super late response. But this should be fixed now!
