### ISSUE TITLE
Run on master branch only

### ISSUE THREAD

**Issue by Tejas2805** [actions/stale#132]
Hi,

Just want to confirm, is there a way to make it on the master branch only?

Or will the Action work on all the branches?

**Comment by embano1** [comment]
Generally speaking issues/PRs are not associated with a branch per se, are they?

**Comment by Tejas2805** [comment]
Yup agree to that. But wish to know is there a way to make it run on a specific branch, if I want to

**Comment by embano1** [comment]
Not sure if it helps, but you can always define custom triggers for your action, but of course it depends on whether this is applicable to the respective Action: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

**Comment by hross** [comment]
We don't have a way to filter PRs specifically (if you are talking about source and target branch as being the filtering mechanisms). We will probably not add that as an enhancement since it is somewhat of a narrow use case.
