### ISSUE TITLE
Remove stale label when issue is tagged with exempt label after marking stale

### ISSUE THREAD

**Issue by embano1** [actions/stale#136]
If an exempt label, e.g. `wip` is added **after** the action ran and marked an issue as `stale` it would be nice to remove the `stale` label by the action in the next run. Right now the code seems to only consider exempt labels for skipping but not removing previously labeled issues.

**Comment by hross** [comment]
I like this idea and may look at making a change. May take me some time so if you want to add the enhancement, feel free to submit a PR and I can review/merge.

**Comment by C0ZEN** [comment]
Good idea.

**Comment by C0ZEN** [comment]
Reopen please?

**Comment by hross** [comment]
Will reopen and see if we get a PR/feedback.

**Comment by C0ZEN** [comment]
Up to avoid stale.

**Comment by C0ZEN** [comment]
Up to avoid stale.

**Comment by chadwhitacre** [comment]
Pretty thrashy. "Up to avoid stale" is the new "+1"? :^P

**Comment by Skeen** [comment]
> Pretty thrashy. "Up to avoid stale" is the new "+1"? :^P

+1 ;)
