### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ZacSweers** [actions/stale#152]
See a number of issues (including my own) go unacknowledged and ultimately marked as stale and closed

**Comment by hross** [comment]
Yes. Can you link the issue? Not everything will be addressed if it is a feature request or enhancement (bugs and important features will be added).

**Comment by hross** [comment]
More detail... I am the primary maintainer of this repo and I look at it once a week. It is pretty stable so changes are slow.

**Comment by ZacSweers** [comment]
#57
