### ISSUE TITLE
Option to ignore issues tied to projects or milestones

### ISSUE THREAD

**Issue by j3parker** [actions/stale#153]
For us, if an issue is part of a project or milestone in our mono-repo it would make sense for it to be exempt from life-cycle rules.

Projects/milestones are a larger group of issues, and it's easier for humans to make a call on whether they can be cleaned up in bulk.

We can work around this today with exemption labels, but it's extra work to add a label in these scenarios, and if an issue is removed from a project/milestone the exemption would still apply if we don't also remove the label.

Maybe options like:

* `exempt-issues-with-project: true`
* `exempt-issues-with-milestone: true`
* `exempt-prs-with-project: true`
* `exempt-prs-with-milestone: true`

(the defaults would be `false` to match current behaviour.)

In terms of implementation/performance, milestones would be the easiest/free because it's included in the issue item object returned by the API (its either `null` (no milestone) or some object). Here's an example: https://api.github.com/repos/kubernetes/kubernetes/issues/33773

However, projects might be harder. The example I linked above doesn't have a milestone but does have a project attached to it, but there is nothing in the issue object to indicate that. So that probably means extra API calls.

What do you think? If this generally sounds like an OK feature I could send a PR for the milestone options to start, since that seems like the safest.

**Comment by j3parker** [comment]
Ah, it looks like project card details are available under a flag: https://developer.github.com/changes/2018-09-05-project-card-events/

**Comment by hross** [comment]
I'm not sure we want to add more options to the stale action that make it even more complex. I think something like this would be better: https://github.com/actions/stale/issues/27

(support a generic query)

I'm not sure I'll have time to invest in that option right now but having a custom query might solve this type of issue without overcomplicating the stale action.

**Comment by j3parker** [comment]
That sounds great; [`no:milestone`/`no:project`](https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-missing-metadata) would satisfy this use-case just fine.

Would you accept a sequence of PRs that:
1. Changed [`listForRepo`](https://github.com/actions/stale/blob/1e5e734da7bd7ea04daf52d9f1c6540e83867b73/src/IssueProcessor.ts#L307) to [`issuesAndPullRequests`](https://octokit.github.io/rest.js/v18#search-issues-and-pull-requests), and then
2. Add an optional `query` argument to this action (merging it into the REST API's `q` parameter)?

**Comment by hross** [comment]
as long as it doesn't break any of the existing functionality I think that sounds great. even better if we get a draft true/false from that query so we can support https://github.com/actions/stale/issues/36

**Comment by hross** [comment]
this might be a little risky of a change because testing is going to have to be "live" only (the unit tests won't work in this case). maybe we can get some other watchers of this repo to help test functionality in their repos before I publish a release.

**Comment by j3parker** [comment]
Ahh I’ll send a PR next week :)

**Comment by afaher** [comment]
Only move forward __

**Comment by Borda** [comment]
@j3parker is there a PR for this or is it already in the codebase?
just for the record, it is similar to #35
