### ISSUE TITLE
Support multiple exempt labels

### ISSUE THREAD

**Issue by skjnldsv** [actions/stale#17]
On the stale bot, we were able to ignore a list of labels from the runs
```yml
# Only if issues that are not triaged
exemptLabels:
  - "1. to develop"
  - "2. developing"
  - "3. to review"
  - "4. to release"
  - security
```

Could be nice if we could as well :)

On another note, the description for the `exempt-issue-label` config is not really appropriate I'd say: `The label to apply when an issue is exempt from being marked stale`. I would go for something like `The label to ignore. Any issues with that label will not be processed.`

**Comment by Francois-Esquire** [comment]
Would be really nice to have this.

**Comment by Alexs784** [comment]
I agree, I would love to have back that option 🙏
