### ISSUE TITLE
Add support for start date option, to ignore issues with activity before that date

### ISSUE THREAD

**Issue by TheOneRing** [actions/stale#174]
Hi our repository has 600+ open issues and I'm afraid this action would mark them all as stale.
Adding the option for a start date sounds handy, it would allow to apply the action only on issues with an activity after the bot was added.

**Comment by TheOneRing** [comment]
Unstale

**Comment by bacongobbler** [comment]
https://github.com/actions/stale/pull/217 might actually help a little here in this regard. While it doesn't solve my particular use case, you could use that to filter out any issues up to a specific start date.

**Comment by bacongobbler** [comment]
It is worth noting that there is a limit on the number of issues/PRs the stale issue bot will filter before it stops, so it will not process all 600+ issues in one go. The default is set to 30 operations, and it always reads from the front of the list (hence why I'm trying to fix that up in #216).

**Comment by TheOneRing** [comment]
While that sounds like a workaround, I don't want to wake up one day and see 600 issues marked as stale :D

**Comment by TheOneRing** [comment]
Unstale.

In the current maintenance state of this repo, maybe the stale bot should be set to a higher limit....

**Comment by C0ZEN** [comment]
I will provide a PR soon.

**Comment by C0ZEN** [comment]
@TheOneRing waiting a review.

**Comment by TheOneRing** [comment]
thx 🥳
