### ISSUE TITLE
Allow mentioning of issue / PR owner

### ISSUE THREAD

**Issue by dsaxton** [actions/stale#177]
I think it would be handy if it were possible to also @ mention the owner of the issue / PR owner when commenting, as this would be more likely to get the attention of that person. Is this currently possible? Ideally one would specify the `stale-pr-message` as a template that references the PR owner as a variable.

**Comment by alecf** [comment]
I'm also looking for this functionality, and might be able to contribute a patch... if there is interest in figuring out what to replace with what to replace what with. In addition, I'd think you might want to pull in a few other fields from the issue if you had it available.

The challenge is that actions already support `${{ .... }}` syntax, so you'd have to use something that does not collide. A few options:

 * `@<assignee>`, `@<user>` etc
 * `@{{assignee}}`, `@{{user}}` etc 
 * `@assignee` `@author` etc

**Comment by sthakkar-rdc** [comment]
I need this. Is it available ? I tried `{{author}}` but it didn't work
