### ISSUE TITLE
Support exempt-issue-labels/onlyLabels

### ISSUE THREAD

**Issue by skjnldsv** [actions/stale#18]
Like the old stale bot, we had `onlyLabels` to force every issue/ to have all of the provided labels before being processed.

```yml
# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels:
- "needs info"
- "0. needs triage"
```

**Comment by DanTup** [comment]
I think the title of this issue isn't very clear - my understanding is that this request is to support listing labels to *include*?

I'd like to see this too - I have an "awaiting info" label, and I'd prefer to only mark those things as stale/close them.
