### ISSUE TITLE
Details required in README

### ISSUE THREAD

**Issue by Gau02** [actions/stale#189]
Information table about each argument and information about required/optional arguments while building an action is missing.
Should we add this information table in README? 🤔

**Comment by hross** [comment]
Would be cool to add. I don't think I'm going to have time to spend on it right now but if you want to submit a PR I can review it.

**Comment by Gau02** [comment]
Sure @hross. I have raised a PR https://github.com/actions/stale/pull/194 for the same. Could you please review it?

**Comment by hross** [comment]
Merged to main
