### ISSUE TITLE
Support different number of days for PRs and issues

### ISSUE THREAD

**Issue by nijel** [actions/stale#214]
I'm currently using Probot Stale and would like to migrate to this action. One thing which doesn't seem to be possible to configure here is different number of days for PRs and issues.

I can see two approaches that would work for me:

* Add `issue-days-before-stale`/`pr-days-before-stale` and `issue-days-before-close`/`pr-days-before-close` settings to override `days-before-stale` and `days-before-close`
* Add `process-issue`/`process-pr` boolean flags to disable processing of given types and I'd configure two action runs

I think second approach is better as that makes it easy to diverge any setting for PR and issues while not making the action more complex with every single such diversion.

**Comment by C0ZEN** [comment]
@nijel I like the idea but IMO the first one is more simple to understand.

**Comment by C0ZEN** [comment]
Also it requires to have dedicated messages for stale-issue-message.

**Comment by C0ZEN** [comment]
I will provide a PR.

**Comment by C0ZEN** [comment]
Up

**Comment by alyssawilk** [comment]
@hross any chance you folks could tag a stale release for this, or should we just pin to specific hashes?
thanks!

**Comment by hross** [comment]
@alyssawilk yup, I am letting it run internally to make sure we don't run into anything before I up the hash.

**Comment by alyssawilk** [comment]
Awesome, thanks for the update!
