### ISSUE TITLE
[Feature Request] Separate only-labels into only-issue-labels and only-pr-labels

### ISSUE THREAD

**Issue by pllim** [actions/stale#219]
Example use case that this request is for:

* Only issue marked as "Close?" will be processed.
* But any PR inactive for 150 days will be processed regardless of labels.

EDIT: Looks like there is an unmerged attempt at #206 ?

Alternative implementation that would also be acceptable: Have option to disable the action for issue or PR, hence allowing the action to be defined twice with different rules, once for issues and once for PRs.

**Comment by pllim** [comment]
Does this mean this request was rejected?

**Comment by C0ZEN** [comment]
@pllim no, it was stale due to inactivity.
You need to rebase the related PR so that it can be merged.

**Comment by pllim** [comment]
Hello. Thanks for the reply but I'm confused. This is an issue. I didn't open any PR.

**Comment by C0ZEN** [comment]
@pllim sorry I thought you were the author of https://github.com/actions/stale/pull/206

**Comment by pllim** [comment]
@C0ZEN , can we re-open this issue since #206 was closed without merge and I am still interested in this feature? Thanks!

**Comment by C0ZEN** [comment]
@pllim I do not have the rights to reopen but you can just create it once again and link this one in the description?
