### ISSUE TITLE
Add statistics after run

### ISSUE THREAD

**Issue by tobiasdiez** [actions/stale#262]
It would be nice to have a basic statistics after the action run, e.g. issues looked at, number of issues marked stale, number of issues no longer stale, number of issues closed etc.

**Comment by tobiasdiez** [comment]
Still relevant, and has a few upvotes already.

**Comment by C0ZEN** [comment]
At some point I am interested to provide a PR for this but I am prioritizing other features right now.

**Comment by C0ZEN** [comment]
@tobiasdiez looking into it right now.
I was thinking that:
- it should be a new option (default at false)
- it should display the information at the end of the logs
- it should display the count of processed issues and PRs (for now, not distinguish but I think it can be cool to have two section, one for the issues and one for the PRs but it's a lot of extra work)
- it should display the count of operations
- it should display all CRD API calls related to GitHub

**Comment by tobiasdiez** [comment]
Thanks for looking into it.

> it should be a new option (default at false)

Not sure if this really needs to be configurable. In case you are not interested in the output, you can simply ignore it (and the computation cost doesn't seem to be high).

> it should display the count of operations
it should display all CRD API calls related to GitHub

At least for my use case, this is not really the information I'm interested in (but maybe other people are). For me, it was more important to see how many issues are newly marked stale and how many issues are no longer stale.

**Comment by tobiasdiez** [comment]
Thanks a lot!

**Comment by C0ZEN** [comment]
@tobiasdiez this is a first draft so feel free to open a new issue if you think that there is some missing stats or if it can be improved somehow.

**Comment by tobiasdiez** [comment]
Thanks for the implementation! 
Currently it prints statistics such as 
```
Statistics
Processed issues/PRs: 233
Operations performed: 28
Fetched issues: 4
Fetched issues events: 10
Fetched issues comments: 10
```

These are great for debugging / analyzing but I was hoping a bit more for user-focused stats such as number of issues marked stale, number of issues no longer stale and number of issues closed.

**Comment by C0ZEN** [comment]
@tobiasdiez and all of those stats were added as well but only display if at least one of the event occurred

**Comment by tobiasdiez** [comment]
Ah ok, thanks! 
May I then suggest to always display, with 0?

**Comment by C0ZEN** [comment]
@tobiasdiez Since there is a lot of stats (and also I have a PR which split the stats between PR and issues) and based on the actions, some could basically display them all if there is a lot of activities and some almost nothing I prefer to have "useful" stats instead of seeing a bunch of nothing...

**Comment by tobiasdiez** [comment]
I would say knowing that no new issues were marked as stale is a useful information but I trust your judgement.
