### ISSUE TITLE
Avoid stale for specific milestone(s) - Like label does

### ISSUE THREAD

**Issue by C0ZEN** [actions/stale#270]
See #236

**Comment by FabianKoestring** [comment]
Thank you very much! Maybe add a option to ignore every issue/pr with any milestone. We use calendar weeks as milestones and have to add a long list of names to `exempt-milestones`. Just an idea. 😉

**Comment by C0ZEN** [comment]
@FabianKoestring haha that's nice that you ask for this feature to be honest because I was planning to do so at first and then I told myself: KISS.
I dunno though if it's better to have a special milestone name or a new option but I hardly see what it can be anyway since the milestone option accept a string, any kind of value could be considered as a milestone as well as an exception.
So going for something like 'exempt-all-milestones' as boolean would be nice.
What do you think?

**Comment by FabianKoestring** [comment]
>@FabianKoestring haha that's nice that you ask for this feature to be honest because I was planning to do so at first and then I told myself: KISS.
I dunno though if it's better to have a special milestone name or a new option but I hardly see what it can be anyway since the milestone option accept a string, any kind of value could be considered as a milestone as well as an exception.
So going for something like 'exempt-all-milestones' as boolean would be nice.
What do you think?

`exempt-all-milestones` - this is genius!

**Comment by C0ZEN** [comment]
@FabianKoestring haha not so much sadly.
Do you think that we should also create the `exempt-all-pr-milestones` and `exempt-all-issue-milestones`?
It seems to me that the need to split the config in half regarding either it's an issue or a pr is somehow a must have these days.

![](https://media3.giphy.com/media/3o6Zt11R527fgtrIJO/giphy.gif?cid=5a38a5a2d4umoaut0992opgowwy1ukma0m47kt9j7xsvzfkz&rid=giphy.gif)

**Comment by FabianKoestring** [comment]
It may be usefull. For our usecase it would be enough to just ignore every pr/issue with a milestone. As soon as somebody handle prs and issues differently it would be nice to have the ability to configure it. 👌
