### ISSUE TITLE
Feature Request: Remove "CLOSED" tag if an auto-closed issue gets reopened

### ISSUE THREAD

**Issue by william76** [actions/stale#278]
Version: v3.0.14

We had an issue get closed through the action script after being marked stale.  After it was marked stale, our developer re-opened the issue.  They did not touch anything else or add any comments, they just re-opened the issue.  The actions/stale bot script did remove the "STALE" flag but it did not remove the "CLOSED_DUE_TO_INACTIVITY" flag that we have set up.  

This left a confusing issue that was open but also had the 'CLOSED' tag assigned to it.

Can we get a new feature added to this to have the script/bot also remove the CLOSED label that gets added to an issue when closed if it's ever re-opened (but not if it has activity but is kept closed since a closed issue can still have activity)?

**Comment by techtanic** [comment]
### +1

**Comment by C0ZEN** [comment]
I can provide a PR today for this @william76.
Just to be sure the only case where the closed label should be removed is when there was some activity in the issue/PR and the option `remove-stale-when-updated` is enabled?

**Comment by william76** [comment]
@C0ZEN Thanks!

We have had some old issues in our repository where some developers didn't 'repoen' them until after the issue got closed and they just re-opened it without touching labels.  

It seems reasonable that the auto-closer would remove both the 'CLOSED' and 'STALE' labels if an issue is re-opened or if it's had new activity which would reset the timer. 

Thanks for having  a look at this!

**Comment by C0ZEN** [comment]
@william76 re-opening a PR update the `updated_at` field from an issue/PR which is already a criteria to know if the issue/PR should be stale or not so nothing to do on this particular case.
The current process will see that the idle days was changed and will remove the stale label if necessary.
Thank you for confirming this logic.
