### ISSUE TITLE
specific properties accidentally removed in 3.0.14?

### ISSUE THREAD

**Issue by samueljseay** [actions/stale#287]
In version 3 of stale options like `days-before-issue-close` were present. For some reason in the 3.0.14 release they have been removed.

Is this an accident?

**Comment by samueljseay** [comment]
Oh I may have been confused here, have `days-before-issue-close` and `days-before-pr-close` not been released yet?

**Comment by C0ZEN** [comment]
@samueljseay nope because it's hard to test this project to @hross is using it internally for like 1 week to ensure that all the new PR are good before releasing.

**Comment by C0ZEN** [comment]
I think having a "release" label and a comment to indicate that a PR and an issue has been released would be cool if it's not already the case.

**Comment by hross** [comment]
I could have made a prerelease version (but I didn't and tested out of main). I just published latest to v3 so everything is up to date now.
