### ISSUE TITLE
onlyLabels requires all labels to be present

### ISSUE THREAD

**Issue by joeveiga** [actions/stale#302]
The `only-labels` option requires all the listed labels to be present in the issue (an AND, not an OR) in order for it to be taken into account. I understand that parameter is sent as is to the api, here: https://github.com/actions/stale/blob/86561461b92875de77a8b2d2e75f004c826e8f45/src/IssueProcessor.ts#L462 
but IMO (and for my use case) it'd be more useful for that option to behave as an OR. Maybe filtering "client side" instead of sending the parameter to the API? Or maybe a whole different config option if we don't want a breaking change?

**Comment by joeveiga** [comment]
Please see #319 . Thanks!

**Comment by C0ZEN** [comment]
@hross this one can be closed since the related PR was merged.
