### ISSUE TITLE
[Feature Request] Separate only-labels into only-issue-labels and only-pr-labels

### ISSUE THREAD

**Issue by pllim** [actions/stale#308]
Example use case that this request is for:

* Only issue marked as "Close?" will be processed.
* But any PR inactive for 150 days will be processed regardless of labels.

There was an unmerged attempt at #206 . This request is a repeat of #219 that was closed by, ironically, the stale bot.

Alternative implementation that would also be acceptable: Have option to disable the action for issue or PR, hence allowing the action to be defined twice with different rules, once for issues and once for PRs.

**Comment by C0ZEN** [comment]
I can provide a PR at some point but I am waiting for my current ones to be processed.
I like the idea to have new options dedicated to issue/pr to customize more if needed.
In fact, most on the features these days are concerning stuff like that where people need different behaviours based on either it's an issue or a pr.

**Comment by C0ZEN** [comment]
I can provide a PR after #327 is merged since it provides a better syntax with the matrix testing than the current milestones (even if the milestones are literally covering all the cases it's very hard to read)

**Comment by kaxil** [comment]
@pllim @C0ZEN @hross We use this action at https://github.com/apache/airflow -- I would like to only check for Stable PRs -- I think `only-pr-labels: ''` or `only-pr-labels: []` should work for disabling the bot for checking "Staleness" on PRs -- can one of you confirm please?

**Comment by C0ZEN** [comment]
@kaxil the default value of `only-pr-labels` is `''` and you can interpret it as `unset`.
The action will ignore it.
To disable the automatic stale of pull requests, you can set the option `days-before-pr-stale` at `-1`.

**Comment by kaxil** [comment]
Actually, I said the opposite, I meant in Airflow we don't want to close Issues as stale.

I have already set `days-before-issue-stale: -1` but it still looks for all those issues (I think - please correct me if I am wrong):

```
[#14604] This issue hasn't a stale label
[#14604] Not marking as stale: shouldBeStale=true, shouldMarkAsStale=false
[#14603] Found issue: issue #14603 last updated 2021-03-04T23:34:58Z (is pr? true)
[#14603] Days before pull request stale: 45
[#14603] This issue hasn't a stale label
[#14603] Not marking as stale: shouldBeStale=false, shouldMarkAsStale=true
[#14601] Found issue: issue #14601 last updated 2021-03-04T14:30:38Z (is pr? true)
[#14601] Days before pull request stale: 45
[#14601] This issue hasn't a stale label
[#14601] Not marking as stale: shouldBeStale=false, shouldMarkAsStale=true
[#14598] Found issue: issue #14598 last updated 2021-03-04T23:10:14Z (is pr? false)
[#14598] Days before issue stale: -1
[#14598] This issue hasn't a stale label
[#14598] Not marking as stale: shouldBeStale=true, shouldMarkAsStale=false
[#14597] Found issue: issue #14597 last updated 2021-03-04T23:39:54Z (is pr? false)
[#14597] Days before issue stale: -1
```

https://github.com/apache/airflow/blob/33910d6c699b5528db4be40d31199626dafed912/.github/workflows/stale.yml#L37-L38

Ideally, I would love to have the action bot not search (and loop) across those issues altogether

**Comment by C0ZEN** [comment]
@kaxil haha sorry for the misunderstood.
Actually, the action fetch a list of issues and PRs altogether (so that they are processed by direction and update date).
So everything is fetched then internally the action will disregard the process of some issues and PRs based on the given options.
This is why you are able to see that in the logs.

Now, to stale something the date is used so passing `days-before-issue-stale: -1` will simply never consider an issue as stale.

**Comment by kaxil** [comment]
Sure, thanks for the reply and for maintaining this repo <3
