### ISSUE TITLE
Action not run

### ISSUE THREAD

**Issue by bonomat** [actions/stale#33]
Hi there, 

good job on this action. We are using it in some of our projects and it works great. 

I thought I cross-post here nevertheless as it might be from interest for you even though I don't think it is an issue with your code:

https://github.community/t5/GitHub-Actions/Action-not-run-and-no-logs-available-action-stale/m-p/42795#M5120

Summary: the action/stale is never run and no logs are available for our repository in https://github.com/comit-network/comit-rs.

source code: https://github.com/comit-network/comit-rs/blob/master/.github/workflows/stale.yml

Cheers,
Philipp

**Comment by MaicolBen** [comment]
I can see it in https://github.com/comit-network/comit-rs/runs/429046842?check_suite_focus=true, but it happens to me as well, the github action does nothing

**Comment by hross** [comment]
Is this still an issue? I see it being run in your repo. See this issue for my comments on how you can debug it: https://github.com/actions/stale/issues/37#issuecomment-614828601

**Comment by MaicolBen** [comment]
In my case, it runs but did nothing, so feel free to close this issue

**Comment by bonomat** [comment]
Hi @hross: sorry for not updating this ticket. It seems to run now :)
