### ISSUE TITLE
[Feature] Only mark issues stale if a maintainer was the last to comment

### ISSUE THREAD

**Issue by tnorling** [actions/stale#346]
It would be great if the stale-bot ignored issues that are waiting for a maintainer to respond. Sometimes it takes us a while to get back to customers and we don't want issues auto-closed if we are the reason the issue is stale. One way you could potentially do this is by reading the repo's CODEOWNERS file to get a list of usernames to check for.

**Comment by C0ZEN** [comment]
@tnorling to sums up, you wish to avoid to stale when there is no comment from a user considered as "maintainer", right?

**Comment by tnorling** [comment]
I wish to avoid labeling as stale/closing when the most recent comment is not from a maintainer.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by tnorling** [comment]
We ended up switching to an internal tool to handle this use case
