### ISSUE TITLE
How to exempt issues linked to a/any project? 

### ISSUE THREAD

**Issue by romainr** [actions/stale#359]
Sometimes issues are not bound to a specific milestone yet (too much to do already, etc...) but should be kept.

Would it make sense to introduce avoiding to close issues attached to at least one project? Sorry if there is a workaround already but I could not find one.

Potentially some new tags could be added, similarly to the existing tags:

```
   exempt-all-issue-milestones / exempt-all-pr-milestones
   --->
   exempt-all-issue-projects / exempt-all-pr-projects
```

**Comment by C0ZEN** [comment]
@romainr yes, it totally makes sense that this feature could be implemented.
Nevertheless it will not be as easy as the milestones to implement since the projects are not part of the issues endpoint](https://docs.github.com/en/rest/reference/issues#list-repository-issues) based on what I saw in the doc.

**Comment by romainr** [comment]
Thanks!

I see, the main idea is that there are 200+ ones, but indeed added 'roadmap' label to avoid closing and sticking the good ones via attaching them to 'milestones'. This is good practice anyway and maybe less option is better than too many :)

**Comment by C0ZEN** [comment]
@romainr well I do prefer the luxury of choice and the simplicity to use the stale action as a consumer.
Like I said, I think that having this feature is a very good idea but only if at the end the implementation will not cost for example 1 API call per issue.
Well, we could still provide this in fact but simply warn about it in the doc.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
Yep, thinking back at it again and I confirm that having this feature would be nice IMO and should just be pointed as not a recommended one if you care about API rate.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
The feature is available on this action https://github.com/Sonia-corporation/stale

**Comment by C0ZEN** [comment]
@romainr this is now possible on this other stale action
See https://sonia-corporation.github.io/stale/docs/issues/inputs/issue-ignore-all-project-cards-input.
