### ISSUE TITLE
Add stale comment when manually stale

### ISSUE THREAD

**Issue by C0ZEN** [actions/stale#378]
See https://github.com/actions/stale/issues/351

**Comment by C0ZEN** [comment]
up

**Comment by pllim** [comment]
Hard to tell from reading the linked issue and this issue. Based on the title, I think I accomplished this without this Action, but rather have github-script post a message when the stale label is applied for a labeled event. 🤷

**Comment by C0ZEN** [comment]
up

**Comment by luketomlinson** [comment]
I don't think this is within the scope of the stale action.
