### ISSUE TITLE
improve onboarding for newcomers: issue template, PR template, template chooser

### ISSUE THREAD

**Issue by HonkingGoose** [actions/stale#396]
## Problems

Current issue template has a wall of text that a contributor needs to remove each time, it also does not contain a logical structure of the things the contributor needs to provide to be a good issue.
The wall of text tries to redirect unwanted stuff, but it's not very convenient, as you cannot click on the provide links and go to the proper place.

There are also no pull request template to guide new contributors.

## Solution:

1. Create proper issue template.
2. Redirect unwanted stuff via the new "issue template" screen that GitHub now offers.
3. Trim down wall of text in issue template as we can use the template chooser screen to redirect unwanted stuff.
4. Create pull request template.
5. Create `config.yml` file (https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

## Do you want a PR from me to fix these items?

If you want, I can make a PR for all the stuff above so you don't have to.
We can then fine-tune the text in those items together.

**Comment by HonkingGoose** [comment]
I'll go make a PR then. 😉

**Comment by C0ZEN** [comment]
up
