### ISSUE TITLE
Is there a CHANGELOG file?

### ISSUE THREAD

**Issue by william76** [actions/stale#399]
I was updating our workflow for the project that I support since we've been using this action for closing out old/abandoned issues and I wanted to see what the updates were from 3.0.14 to 3.0.18 but I don't see a CHANGELOG file.

Do you guys track this somewhere that I'm missing?  If not it would be handy to have that information so I can know if I should upgrade and/or what new features I should look into turning on or if a behaviour changes etc.

Thanks!

**Comment by C0ZEN** [comment]
@william76 I agree. The changelog is not hard to maintain and is very nice to have. Right now you could just check the release notes to have these information. Basically to have this the changelog should be created with release made actually by @hross

**Comment by william76** [comment]
bump :smile:

**Comment by C0ZEN** [comment]
Looking at this again and I love automated changelogs based on the commits but I made a PR to have automated release covering this case like 3 months ago and it was not approved.
So, by hand seems the way and it's fine with me.
So maybe having this in the contribution process and having each PR updating it would be fine with me and also more user-friendly.
I can provide a PR soon since some of my PRs were merged today/yesterday and some are waiting.

**Comment by hross** [comment]
Weighing in here, I don't anticipate this repo changing enough for a changelog, long term. It would be nice to have but auto-generating it or making it have to manually update a bunch seems like a lot to do for a low churn action.

The releases page does have a changelog of sorts ([each release has lists of features](https://github.com/actions/stale/releases)) so I think that's enough for this project, even though I know it's not the most convenient.

**Comment by C0ZEN** [comment]
@hross and what about https://github.com/conventional-changelog/standard-version?

> Use of standard-version only affects your local git repo - it doesn't affect remote resources at all. After you run standard-version, you can review your release state, correct mistakes and follow the release strategy that makes the most sense for your codebase.

I think that this tool seems quite nice based on how you release and has the advantage to take care of the grunt work without forcing any hand on the process.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
Also, why use a patch increment in the release instead of the minor one when adding new features?
