### ISSUE TITLE
Option to only mark issues with a certain tag

### ISSUE THREAD

**Issue by AlphaMycelium** [actions/stale#40]
It'd be nice to have an option to only run on a certain label (the opposite of `exempt-issue-label`), for example to only process issues labelled as `question`. Of course this should be implemented for PRs as well.

**Comment by dev-zero** [comment]
It seems that this was implemented shortly after the last release in `master`, but not documented:

https://github.com/actions/stale/blob/6127f8ef7a31ffd6d742703b46302161e932e296/src/main.ts#L44

**Comment by AlphaMycelium** [comment]
Ah, this issue was addressed by #22 and not linked. Thank you!
