### ISSUE TITLE
[Feature] Get the information about the staled issues

### ISSUE THREAD

**Issue by flaxel** [actions/stale#452]
When the action has run, it would be nice to get the data of the staled issues with author. This way, you could use the data to use other actions that, for example, send a Slack message to the author.

**Comment by C0ZEN** [comment]
@flaxel do you wish to provide a PR?

**Comment by flaxel** [comment]
I did some research and I will try it. 😄

**Comment by C0ZEN** [comment]
@flaxel I would recommend an approach with a generic class to alter the outputs of the action since if you achieve to do a first version, I see a bunch of new features that can follow.

**Comment by flaxel** [comment]
I have created a first draft and it should work. But I don't get any output in the test action. Is this normal or should there be some text? If it is the same behaviour as with my actions, then they are not updated until the branch is merged, so it should be ok.

> I would recommend an approach with a generic class to alter the outputs of the action

What do you mean by the approach? Wouldn't it be enough to return the classes as they are or is it better to control the outputs and not output everything? Do you want to create one class per output? At the end I will write some tests. 👍 

I would stop for today and continue later. 😄
