### ISSUE TITLE
Option to ignore new comments on stale issues

### ISSUE THREAD

**Issue by jeremystretch** [actions/stale#470]
## The problem
Often when an issue is marked stale, it prompts the OP to post "bump" comments to avoid having the issue marked as stale (undermining Stale's entire purpose). We can set `remove-stale-when-updated` to false to prevent the automatic removal of the stale label, however Stale will not (as far as I can tell) proceed with closing an issue that has received at least one comment since the stale label was applied.

(Our workflow is for a maintainer to review new comments on stale issues, and to manually remove the stale label as appropriate.)

Below is an example:

```
[#5442] Found this issue last updated at: 2021-04-23T19:21:04Z
[#5442] The option only-labels (​https://github.com/actions/stale#only-labels​) was not specified
[#5442] └── Continuing the process for this issue
[#5442] Days before issue stale: 60
[#5442] The issue is not closed nor locked. Trying to remove the close label...
[#5442] There is no close label on this issue. Skip
[#5442] This issue has a stale label
[#5442] The option any-of-labels (​https://github.com/actions/stale#any-of-labels​) was not specified
[#5442] └── Continuing the process for this issue
[#5442] This issue has no milestone
[#5442] └── Skip the milestones checks
[#5442] This issue has no assignee
[#5442] └── Skip the assignees checks
[#5442] This issue is already stale
[#5442] Checking for label on this issue
[#5442] Issue marked stale on: 2021-04-14T04:11:47Z
[#5442] Checking for comments on issue since: 2021-04-14T04:11:47Z
[#5442] Comments not made by actor or another bot: 1
[#5442] Issue has been commented on: true
[#5442] Days before issue close: 30
[#5442] Issue has been updated: false
[#5442] Stale issue is not old enough to close yet (hasComments? true, hasUpdate? false)
[#5442] 1 operation consumed for this issue
```

I believe the relevant logic is [here](https://github.com/actions/stale/blob/e8845990724aed85a03e40a7f08c25673821a934/dist/index.js#L555): Because `hasComments` is true, the issue won't be closed.

## The solution

At a glance, I see two potential solutions:

1. Infer from `remove-stale-when-updated` whether to close issues with both a stale label and comments: If false, assume that we should close a stale issue even if it has a comment.
2. Introduce a new configuration option (e.g. `ignore-stale-comments`) to explicitly control this behavior.

**Comment by C0ZEN** [comment]
I think it's what you need https://github.com/actions/stale/pull/390.
You tell me ;)

**Comment by jeremystretch** [comment]
> I think it's what you need #390.

I don't think that would address this issue. The problem I'm running into is that even when the stale label is left applied, issues are not being closed.

**Comment by checktheroads** [comment]
Having looked through #390, I don't think it will address this issue. It _almost_ does, but not quite. In our case, we do _not_ want Stale to remove the stale label (the changes in #390 assume `remove-stale-when-updated` or `remove-stale-when-commented` are `true`), but we _do_ want Stale to close an issue if with a stale label, regardless of whether or not it has comments.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by jeremystretch** [comment]
The irony, it burns. :laughing:

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up
