### ISSUE TITLE
Utilize toolkits collapsible logs

### ISSUE THREAD

**Issue by luketomlinson** [actions/stale#475]
## The problem
Currently, each issue/PR that is processed has a [#NUMBER] appended to the log line. 
## The solution
I think we can utilize the `core.startGroup` and `core.endGroup` [functionality](https://github.com/actions/toolkit/tree/main/packages/core#logging) in the `IssueLogger` to make these logs a little easier to read.

**Comment by C0ZEN** [comment]
![](https://i.imgur.com/zEYj61M.png)
Damn, it's way less scary now!
