### ISSUE TITLE
Question : Is there a way to assign certain label to only issues which are unlabeled?

### ISSUE THREAD

**Issue by kanika1894** [actions/stale#476]
## Describe your issue

The requirement is to assign a label to an issue only if doesn't have any label assigned. can this be achieved using this action?

**Comment by C0ZEN** [comment]
@luketomlinson for this kind of issue, it would be nice to allow to open a blank issue in the repo settings.
WDYT?

**Comment by C0ZEN** [comment]
@kanika1894 I don't think so however I think it can be useful to have something like `exempt-all-labels`.

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up
