### ISSUE TITLE
Split the documentation and the options between issues and PRs

### ISSUE THREAD

**Issue by C0ZEN** [actions/stale#493]
## The problem

From https://github.com/actions/stale/pull/473#discussion_r645111321.

We have too many options and few options are only available for PRs.
The documentation, as well as the code, would be cleaner if we consider both workflows as unique instead of trying to mix them.

## The solution

Split everything in half inside the documentation.
Remove every options that alter both issues and PRs (shortcuts).

I will provide a PR for this.

**Comment by C0ZEN** [comment]
@luketomlinson once the current PR are merged, I can work on this one FYI.
Huge PR incoming 👀

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by ciaranevans** [comment]
@C0ZEN I see you on a lot of the issues and this one is slightly related to a use-case I have - I'm looking through the documentation and I can't figure out if I can just disable making PRs stale completely?

I'm only interested in Issues, we don't have a unmanageable amount of PRs to worry about...

**Comment by C0ZEN** [comment]
@ciaranevans you can set https://github.com/actions/stale#days-before-pr-stale and https://github.com/actions/stale#days-before-pr-close to -1.

**Comment by ciaranevans** [comment]
@C0ZEN Ah awesome, thanks!

**Comment by C0ZEN** [comment]
up
