### ISSUE TITLE
Pros and cons vs the stale bot

### ISSUE THREAD

**Issue by julien-c** [actions/stale#53]
Out of curiosity, what are the pros and cons of this vs. the [stale bot](https://github.com/probot/stale)

Is it a more recent rewrite using GitHub Actions?

Are there any difference in use cases that they respectively unlock?

**Comment by hross** [comment]
Usage is situational. I don't have insight into the original history of the stale action so I can't comment on "why". I don't think of it as a more recent rewrite of the stale bot but I do think there are pro's and con's to both.

Overall I think this action is probably less mature than stale bot, but getting there (see our issue list for a few things stale bot does that we should probably do). Eventually we will reach somewhat feature parity but for now if stale bot works, use it.

One advantage of using this action is traceability. You can go to the actions logs and see what it did, or set debug mode and see what it **will** do without doing anything.

Right now I think stale bot is more mature but I hope in the future that the stale action provides feature set and traceability.

**Comment by julien-c** [comment]
Thanks @hross
