### ISSUE TITLE
[Feature Request] Add option to delete branches of closed pull requests

### ISSUE THREAD

**Issue by MichaelJJ** [actions/stale#544]
## The problem
If users have closed a Pull Request, but did not choose to delete the branch, many stale branches get left in the history.

## The solution
Add option or update the stale Pull Request logic to also delete branches of closed Pull Requests.  There could also be an option to limit to delete branches if the Pull Request has been closed longer than x days.

**Comment by C0ZEN** [comment]
@MichaelJJ is it not the purpose of https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches?

**Comment by MichaelJJ** [comment]
This only functions if the PR was merged.  If a user closes a PR, the branch is not auto-deleted.

**Comment by C0ZEN** [comment]
OK, in that case why not, I could provide a PR, but it's not in my priorities immediately.

**Comment by C0ZEN** [comment]
up
