### ISSUE TITLE
Allow to pass team URL to exclude issues/PR

### ISSUE THREAD

**Issue by sculpt0r** [actions/stale#548]
## The problem
There is an option: https://github.com/marketplace/actions/close-stale-issues#exempt-assignees which allows listing each person so the PR / issue won't be processed. It requires keeping up to date this list each time a new member of the GH team joins or leaves.

## The solution
Maybe it will be good to paste here only the URL to the team, so there will be no need to list team members manually?

**Comment by C0ZEN** [comment]
up
