### ISSUE TITLE
Adding a possibility to tag/mention team members in the bot comment

### ISSUE THREAD

**Issue by ayakalauova** [actions/stale#558]
It would be cool if there was an opportunity to have a placeholder string (like "@author" or "@assignee") to be able to tag them in the comment section

**Comment by mikkilevon** [comment]
Maybe add a config of `enable-mention-of-assignees: true/false`? This could be also added for author and PR reviewers. The mentions could be added after the comment.

**Comment by C0ZEN** [comment]
@luketomlinson WDYT? You said you wish to reduce the number of new options, nevertheless meanwhile there are requests for more.
What is the long run plan?

**Comment by luketomlinson** [comment]
@C0ZEN I'm thinking through this. I think part of our issue is that we have essentially 3x the number of inputs for a default/pr/issue, so scrolling through the readme, it feels somewhat enormous and hard to understand. A thought (though it might be more confusing), is to have some kind of bit mask for options, like 1 for issues, 2 for PRs and 3 for both.

**Comment by luketomlinson** [comment]
@ayakalauova Do you have an example of how this might work? Are you wanting to put something like @author in the stale comment itself?

**Comment by C0ZEN** [comment]
@luketomlinson improving the doc is something I have in the pipe as well since a long time and this is why I am no longer providing new PR; I wish to wait for the other that I opened then will take the time to provide those improvements; in particular the one that remove the "generic" options to only keep "issue" or "pr" options.

**Comment by C0ZEN** [comment]
I think she would like to have “smarter” comments to ping the author.

**Comment by ayakalauova** [comment]
@luketomlinson exactly, so that I can put smth like @author and the bot would tag this person

**Comment by mikkilevon** [comment]
I've been looking into this for a bit and the problems I see with it are
1. Github API does not provide these for PR's when querying for Issues (In Github PRs are a type of Issue). That would mean another API call to get just open PRs and mash the results together.
2. The templates cant use @ author or @ reviewer @ assignee as they are actual Github users. The template would need to be matched to something like {author} etc

Would this be a viable starting point?

**Comment by C0ZEN** [comment]
@mikkilevon 

> The templates cant use @ author or @ reviewer @ assignee as they are actual Github users. The template would need to be matched to something like {author} etc

Definitely, the message template should differ and use a syntax different from GitHub to just replace the occurrences with the right information.

> Github API does not provide these for PR's when querying for Issues (In Github PRs are a type of Issue). That would mean another API call to get just open PRs and mash the results together.

I think multiple API calls at the beginning of the workflow is OK but based on the initial feature request on this ticket which cover the original author and the assignees, the API already give this information when calling the endpoint, so I do not think you have to do a specific call.
See https://docs.github.com/en/rest/reference/issues

**Comment by mikkilevon** [comment]
Ah it does provide author and assignees but not reviewers as those would be also a good idea to mention 🤔

**Comment by C0ZEN** [comment]
up
