### ISSUE TITLE
README has error on start-date example

### ISSUE THREAD

**Issue by JamieDanielson** [actions/stale#561]
## Describe your issue

The README example for [start-date](https://github.com/actions/stale#start-date) in the [Usage](https://github.com/actions/stale#usage) section shows '2020-18-04' when it should be '2020-04-18'.

## Further context

There is a function getHumanizedDate that joins as day, month, year… but the code otherwise uses ISO format which is year, month, day. The code seems to work, but the README example is incorrect and if copied verbatim, someone could apply stale to older issues accidentally. It's obviously a minor change, but let me know if I should submit a PR.

**Comment by C0ZEN** [comment]
My bad, but sure you can open a PR.
