### ISSUE TITLE
Allow option to exclude weekends from total time

### ISSUE THREAD

**Issue by cschear** [actions/stale#564]
## The problem
We would like to keep the total time open pretty low - but weekends cause items to be flagged early. For example we would like it to be 3 weekdays - but currently a PR opened on Friday would be stale on Monday.

## The solution
Allow an option to exclude weekends from the total time open.

**Comment by cschear** [comment]
Maybe using something like this:
https://stackoverflow.com/a/21465288

**Comment by luketomlinson** [comment]
Hi @cschear thanks for opening an issue. I am not sure that such a specific special case is the best path forward for this action. My worry is that once we start special casing for weekends it might spiral into many special cases (weekends, holidays, leap years, etc). 

That being said, I'll leave this issue open for a bit to see if there is a larger desire for this feature and maybe we can reevaluate if there is a large demand for this feature.

**Comment by rkdrnf** [comment]
Also need this feature. We also trying to maintain low stale time (2 or 3days) but because of the weekend counted, we are using 4 days instead now.

Counting holidays as working days wouldn't much matter because those are relatively rare cases.

**Comment by shreyasbharath** [comment]
Can we revive this please? It's a pretty basic use case

**Comment by irm-codebase** [comment]
I think this should be re-considered. At least weekends. It's absolutely crucial for most companies or projects in order to avoid mistakes.

**Comment by charleseasyvest** [comment]
I also vote for this feature

**Comment by samgdotson** [comment]
Seems like it should be the default.

**Comment by whartley94** [comment]
Bump
