### ISSUE TITLE
Auto-rebase + stalebot questions

### ISSUE THREAD

**Issue by wimo7083** [actions/stale#583]
## Describe your issue

We have some automation that will auto-rebase and keep branches up to date. We default to "on" for this behavior so favor individuals who open a PR and merge within a few hours don't have to worry about triggering the behavior with labels.

Prior to enabling this feature, we were using stale to perform cleanup actions.

The auto-rebase actions are triggered from a singular GitHub third-party application we have configured.

Is there a recommended method to ignore updates that originate from a certain user/ GitHub integration?

## Further context

N/A

**Comment by C0ZEN** [comment]
Nope
