### ISSUE TITLE
Opposite of exempt-all-assignees

### ISSUE THREAD

**Issue by kingthorin** [actions/stale#596]
## The problem
It would be nice if there was a way to only add stale comments on issues/PRs that are actually assigned (to remind people of their commitments).

## The solution
Add an opposite flag like `include-only-assigned: true` (Default `false`).

I apologize if this is somehow already possible and I missed it.

**Comment by kingthorin** [comment]
Any thoughts or input on this?

Have I missed an alternative to accomplish the same?

**Comment by kingthorin** [comment]
Well it would be nice if this was addressed….

**Comment by kingthorin** [comment]
Nope not stale, still functionality that people could use….. :cry:

**Comment by ushio117** [comment]
I don't understand but I want to participate. That's my honest comment.

**Comment by kingthorin** [comment]
No bot still not stale but also still not actioned by project maintainers

**Comment by C0ZEN** [comment]
@kingthorin because there is no maintainer in terms of new features.

**Comment by kingthorin** [comment]
🤷‍♂️Had to add some sort of update for the bot

**Comment by kingthorin** [comment]
Poke, still looking for this.

**Comment by C0ZEN** [comment]
More precisely, would you like the processing to only add stale comments without a stale label?
So that it is never closed?

**Comment by kingthorin** [comment]
Interesting question. I think that's already doable. At least I know my projects have been getting comments/labels without anything being closed. (`days-before-close: -1`) I assume there's a way to skip labeling, I haven't bothered to look.

Mainly I was just looking for a way to reduce spam'ish updates. For most of the projects I work with there's little point in the action/bot updating issues which aren't assigned (like this one). We would rather that it was more of a reminder to assignees that they've got something outstanding which they should be working on.

**Comment by C0ZEN** [comment]
OK, so basically, in other words, you wish to process only issues when there is an assignee?

**Comment by kingthorin** [comment]
Exactly.

**Comment by C0ZEN** [comment]
Willing to do that but on this repo https://github.com/Sonia-corporation/stale/issues/559
I no longer add new features here

**Comment by kingthorin** [comment]
@COZEN thanks for that. We'll have to decide which way to go. I'll discuss with the team. (My hesitation is around fragmentation and upkeep.)

**Comment by kingthorin** [comment]
No stale bot it STILL isn’t stale, we’ll at least not __more__ than this entire repo.

**Comment by kingthorin** [comment]
/le sigh

NO bot still not stale, simply not actioned.

**Comment by kingthorin** [comment]
/le sigh

NO bot still not stale, simply not actioned.

**Comment by kingthorin** [comment]
@JoannaaKL thanks for tackling this!
