### ISSUE TITLE
Feature Request: Stale Branch Management

### ISSUE THREAD

**Issue by stavrosgogos-bc** [actions/stale#620]
## The problem
Similar to how stale issues and PRs can become problematic, stale branches can clog a repository if not well managed.

## The solution
Create similar capability to management of stale issues and PRs that tracks when a branch becomes stale. A request to delete the stale branch could be sent to the branch creator and if the request is not replied to in a certain window, then the branch will be deleted.

**Comment by psypuff** [comment]
@dsame any chance to get this feature request considered?

This action supports deleting branches of stale PRs once deleted. Not all branches mature into PRs though and this action ignores such. There are a bunch of community actions tackling this exact issue but we'd appreciate this capability in an official one (could be a separate action if that makes more sense to you).
