### ISSUE TITLE
Placeholders for parameters in messages

### ISSUE THREAD

**Issue by victorhurdugaci** [actions/stale#635]
Hello,

This is a total nitpick request and it's not preventing us from doing anything. It's just a nice to have :)

## The problem

Today we're defining our configuration like:

```yaml
stale-issues-message: Looks like this issue has not been updated in 30 days. Is it still needed?
days-before-issue-stale: 30
```

## The solution

It would be nice if the message could contain a placeholder so we don't repeat the "30". Something like:

```yaml
stale-issues-message: Looks like this issue has not been updated in {days-before-issue-stale} days. Is it still needed?
days-before-issue-stale: 30
```

**Comment by C0ZEN** [comment]
Such feature for templating is very neat for other requests that I saw to have the possibility for example to mention the author in the action comment.

**Comment by SvenStaehs** [comment]
Can this issue/request be revived? I would very much like this! Having to hardcode values in the message is quite nearly painful for me 😉
