### ISSUE TITLE
Allow enumerating only issues / only pull requests

### ISSUE THREAD

**Issue by thalesmg** [actions/stale#649]
## The problem

The previous stale bot [allowed users](https://github.com/probot/stale/blob/7510fac863900a98057436d308e9fe21bbe314ec/README.md?plain=1#L66) to configure it to only consider either issues or pull requests, thus not spending operations on unwanted items.

## The solution

Allow users to disable enumeration of pull requests or issues, so operations are not spent on those.

**Comment by thalesmg** [comment]
Still an interesting feature. :slightly_smiling_face:

**Comment by C0ZEN** [comment]
FYI, @thalesmg [made it](https://sonia-corporation.github.io/stale/docs/issues/inputs/issue-processing-input) through this [other stale action](https://github.com/Sonia-corporation/stale).
