### ISSUE TITLE
Marking Issues as Stale Incorrectly

### ISSUE THREAD

**Issue by fishcharlie** [actions/stale#65]
This issue got marked incorrectly as Stale: https://github.com/dynamoose/dynamoose/issues/543

As you can see that issue has the `status:todo` label on it. But in my workflow, you can see that `exempt-issue-labels` includes `status:todo` label as one of the exempt labels.

https://github.com/dynamoose/dynamoose/blob/ff49d9727a0d9b9b7d883c3dec76ad3734b1f05a/.github/workflows/cron.yml#L16

Why did this issue get marked as stale?

**Comment by dev-zero** [comment]
you've pinned the version of this action to v1 from 2019 which doesn't seem to have that option yet according to PR #19 which was merged 19 days ago.
