### ISSUE TITLE
Question: how to define labels that contain special characters?

### ISSUE THREAD

**Issue by keunes** [actions/stale#654]
Hello,

I would like to create a workflow using labels with special characters: `Close reason: stale / reject`. However, in the documentation I only see labels with dashes, and GitHub (in the URL) encodes these characters. What should I add in the workflow file for the label I mention above?

Many thanks!

**Comment by C0ZEN** [comment]
@keunes I added your label on my repo and I tested this request:

```
query GetLabelByName($owner: String!, $repository: String!, $labelName: String!) {
  repository(name: $repository, owner: $owner) {
    label(name: $labelName) {
      name
      id
    }
  }
}

{
  "owner": "sonia-corporation",
  "repository": "stale",
  "labelName": "Close reason: stale / reject"
}
```
From https://docs.github.com/en/graphql/overview/explorer.
It works fine with the https://github.com/Sonia-corporation/stale action at least.
You can give it a try.

**Comment by keunes** [comment]
Ok, we'll give it a try, thanks!

**Comment by keunes** [comment]
Hi @C0ZEN,

Sorry to bother you. I created a PR and we can merge it, but GitHub action says there's an error in the workflow:
https://github.com/AntennaPod/AntennaPod/actions/runs/1664747087/workflow

Would you mind having a look? I don't really have an idea - to me everything seems fine.

**Comment by rootwork** [comment]
@keunes Just driving by: It looks like the YAML file for the workflow is invalid, but the error message is misleading -- it's because of the apostrophes you have in the messages on lines 24-25. Surround those values with double-quotes instead of single-quotes.

https://yamlvalidator.com is helpful for these kinds of errors.

**Comment by keunes** [comment]
Awesome, thank you @rootwork! Will save that URL :)

**Comment by keunes** [comment]
That seems to have worked. Thanks both for the help!
