### ISSUE TITLE
Ability to set `only-milestones`

### ISSUE THREAD

**Issue by jpmcb** [actions/stale#657]
## The problem

This is a two fold problem I don't know how to tackle with `actions/stale`'s current options:

- I want the ability to point the stale action at just a certain milestone or two. Within my projects, I use a `icebox` milestone that contains PRs and issues that may or may not have bandwidth to be tackled. As the `icebox` milestone grows, I want the stale action to label/close issues and PRs _only within that milestone_, thus keeping the `icebox` as lean as possible.
- I still need the default behavior of the stale action labeling and closing issues and PRs that are _not_ in _any_ milestone.

I thought of tackling this by adding a list of current milestones in `exempt-milestone` but that would require me to periodically update the action's config to be up to date with the dynamic list of milestones that may be present. This seems error prone and a poor use of powerful automation.

## The solution

Add a `only-milestones` option that takes a list of milestones that the stale bot should _only_ check for stale issues / PRs. Using the `only-milestones` option will continue to enable the default behavior of labeling / closing PRs and issues that _don't have a milestone_. Example:

```yaml
only-milestones: "icebox, wont-fix"
```

**Comment by jpmcb** [comment]
Not stale - still a valid request. @actions/actions-runtime - anyone able to look at this and triage?

**Comment by C0ZEN** [comment]
@jpmcb not on this repo, but if you are interested, I could prioritize this within the week here https://github.com/Sonia-corporation/stale/issues/310

**Comment by jpmcb** [comment]
Would still be nice as a feature!! 😄

**Comment by jpmcb** [comment]
Ping. Still relevant. Not stale. Anyone around to look at this?
