### ISSUE TITLE
How to test safely

### ISSUE THREAD

**Issue by mhdawson** [actions/stale#677]
## Describe your issue

I'd like to test our use of the action before having it run on all of our issues. Ideally I could have it run on 1 or a small subset of the issues which meet the stale criteria.  

My first attempt was to add a new label to the issue I wanted to be processed, but that addition caused the issue to no longer be stale.

I've looked through all of the options and I can't come up with a way to have it run on just a few issues so that I can validate that the right message is posted to the issue when it is considered stale.

Related but different I would also like to limit the number of issues marked stale per day once we enable in order to avoid a flood of notifications and updates.  I don't seem to be able to find an option for that either.

Any suggestions?

**Comment by C0ZEN** [comment]
The [start-date](https://github.com/actions/stale#start-date) option seems about just what you need.
So that your action will only process the new items.

**Comment by mhdawson** [comment]
@C0ZEN thanks I'll think about that. What I had though of since posting was setting the stale days so that only a few out of the list at the end would be processed.

**Comment by mhdawson** [comment]
I'm going to close, I'm stuck with manually updating the date/running a few times a week to slowly mark a new batch per week to catch up, but don't have time to PR in an improvement myself.
