### ISSUE TITLE
stale only in PR's

### ISSUE THREAD

**Issue by gabsmprocha** [actions/stale#688]
## Describe your issue

Hi everyone, in my workflow I just set the` days-before-pr-stale` and `days-before-pr-close `parameters, is there a way to prevent this from applying to issues? I would like the action to be just for PR's. I believe that by setting only the PR parameters it would only apply to PR's, but it is applying to issues as well

**Comment by C0ZEN** [comment]
@gabsmprocha you can pass to `days-before-issue-stale` `-1` so that it's not enabled.

**Comment by gabsmprocha** [comment]
> @gabsmprocha you can pass to `days-before-issue-stale` `-1` so that it's not enabled.

it works, tks!! @C0ZEN
