### ISSUE TITLE
randomize ordering when operations-per-run is in effect

### ISSUE THREAD

**Issue by bgehman** [actions/stale#692]
## The problem
[operations-per-run](https://github.com/actions/stale#operations-per-run) is handy to not run up against the github api rate-limiter, however, every time the action runs: it tries to process the same (default `30`) issues that it did on the prior runs.  This has the affect that the stale-bot is not making progress on large backlogs over time.

## The solution
Prefer to randomize the ordering, so that [operations-per-run](https://github.com/actions/stale#operations-per-run) randomly picks which issues to process.  This will have the effect of eventually (randomly) seeing every issue, instead of always only looking at the first (or last) 30 issues by default provided by the [operations-per-run](https://github.com/actions/stale#operations-per-run) and [ascending](https://github.com/actions/stale#ascending) config settings.  Thanks.

**Comment by leonardehrenfried** [comment]
I'm facing the same issue. I'm wondering if a PR would be accepted. A quick look at the code suggests that this could be the place to change it: https://github.com/actions/stale/blob/main/src/classes/issues-processor.ts#L534-L559

**Comment by sakiskaliak** [comment]
I am wondering if actually starting with the oldest PRs would fix this, without a need to randomize.
