### ISSUE TITLE
Skip stale on some pull requests according to the label

### ISSUE THREAD

**Issue by gabsmprocha** [actions/stale#706]
Hi everyone! Is there any parameter that I can pass to stale action ignores a pull request that contains some custom label, for example?

**Comment by luketomlinson** [comment]
You can use [`exempt-pr-labels`](https://github.com/actions/stale#exempt-pr-labels)

**Comment by gabsmprocha** [comment]
> You can use [`exempt-pr-labels`](https://github.com/actions/stale#exempt-pr-labels)

tks @luketomlinson
