### ISSUE TITLE
Unexpected input(s) 'remove-stale-when-updated', 'exempt-pr-labels', 'exempt-issue-labels'

### ISSUE THREAD

**Issue by avagin** [actions/stale#708]
## Describe your issue

https://github.com/checkpoint-restore/criu/actions/runs/209958470
```
Unexpected input(s) 'remove-stale-when-updated', 'exempt-pr-labels', 'exempt-issue-labels', valid inputs are ['repo-token', 'stale-issue-message', 'stale-pr-message', 'days-before-stale', 'days-before-close', 'stale-issue-label', 'exempt-issue-label', 'stale-pr-label', 'exempt-pr-label', 'operations-per-run']
```

What does this warning mean?

And we see that the stale action closed issues and pr-s that have labels from the 'exempt-pr-labels and exempt-issue-labels lists:
https://github.com/checkpoint-restore/criu/issues?q=is%3Aclosed+label%3Ano-auto-close+

Thanks in advance.

**Comment by luketomlinson** [comment]
hi @avagin, what version of stale are you using? Can you post your yaml?

**Comment by avagin** [comment]
@luketomlinson https://github.com/checkpoint-restore/criu/blob/criu-dev/.github/workflows/stale.yml

**Comment by luketomlinson** [comment]
@avagin You are pointing to `actions/stale@v1`. Could you try doing `actions/stale@v4`?
