### ISSUE TITLE
Do you have to close PRs/Issues?

### ISSUE THREAD

**Issue by JamesSingleton** [actions/stale#74]
So since discussions isn't enabled yet for this repo, I shall ask my question here... Is there a way to have this action just mark something a stale but not close the PR or issue? Often times people open an issue and there is no follow up, but we also don't want to close the issue because they haven't gotten back to following up in a certain amount of time. It looks like the closing is required

```
daysBeforeClose: parseInt(
    core.getInput('days-before-close', {required: true})
),
```
Would there be any opposition to not making this required? Furthermore, would there be any opposition to making the marking of stale and closing different between issues and PRs? For example, maybe someone wants to close a PR immediately after being marked as stale but might want to close an issue 2 days after.

**Comment by hross** [comment]
@JamesSingleton set `daysBeforeClose` to `-1` in the config and the bot won't close any issues 😄 .

If you want to separate PR/issue days before close/stale that seems interesting to explore. Maybe we would default to the single value but you could add a PR setting to change it for PRs.
