### ISSUE TITLE
Bot adds stale label then removes

### ISSUE THREAD

**Issue by fishcharlie** [actions/stale#77]
As you can see in the following event, the `github-actions` but added the stale label, then removed it right away. Why is this?

https://github.com/dynamoose/dynamoose/issues/893#event-3358771393

You can also see my workflow file here:

https://github.com/dynamoose/dynamoose/blob/master/.github/workflows/cron.yml

**Comment by Tejas2805** [comment]
I have the same issue. Workflow pattern is same too.

**Comment by hross** [comment]
This is a bug 😄. I'm fixing it now and changing the debug logging to info so you can see what the bot does in the logs every time (this will make cases like this much easier to troubleshoot).

**Comment by DanTup** [comment]
I'm seeing this too. I thought it might have been related to #73, though it doesn't seem to be fixed after that (or at least, the issues haven't been re-tagged since).

**Comment by hross** [comment]
Fixed here: https://github.com/actions/stale/pull/83

**Comment by DanTup** [comment]
@hross thanks! Do we need to do anything for existing issues, or will they automatically be re-labelled when you publish the next version (assuming we're using `@v3` or `@master`)?

**Comment by hross** [comment]
I republish the main tag so as long as you're not pinned to a minor version (pinned to v3) it should just fix itself. let me know if you see any other issues though. I have tests but its quite hard to backdate issues and test certain features of stale.

**Comment by DanTup** [comment]
@hross it doesn't seem to have fixed itself, here's an example of one where it previous added/removed the tag, and hasn't subsequently put it back:

https://github.com/Dart-Code/Dart-Code/issues/2383
