### ISSUE TITLE
Make `not_planned` the default close-issue-reason

### ISSUE THREAD

**Issue by danielcompton** [actions/stale#789]
## The problem

Currently, everyone who uses actions/stale will need to know to configure the `close-issue-reason` setting to `not_planned` to get the new close type - https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/

## The solution

Make the default value `'not_planned'` instead of `''`. The reason matches the use in stale - "Won't fix, canceled, duplicate, **stale**"

**Comment by davorpa** [comment]
bump

It have a current PR fullfilling requirements #807

**Comment by luketomlinson** [comment]
Released in `v6`: https://github.com/actions/stale/releases/tag/v6.0.0
