### ISSUE TITLE
Issue gets marked stale and gets closed immediately even though days-before-close has not expired

### ISSUE THREAD

**Issue by fjeremic** [actions/stale#84]
This is with the latest v3 tag using commit (b6f9559) which is the latest as of today. This is the log output from the run:

https://github.com/eclipse/omr/runs/709719104?check_suite_focus=true

There is a problem towards the end in eclipse/omr#3847:

```
Found issue: issue #3847 - Just-In-Time code patching framework used in CS read barrier  last updated 2019-09-13T12:54:23Z (is pr? false)
Marking issue stale because it was last updated on 2019-09-13T12:54:23Z and it does not have a stale label
Marking issue #3847 - Just-In-Time code patching framework used in CS read barrier  as stale
Found a stale issue
Checking for label stale on issue #3847
Issue #3847 marked stale on: 2020-05-26T14:44:21Z
Checking for comments on issue #3847 since 2020-05-26T14:44:21Z
Comments not made by fjeremic or another bot: 0
Issue #3847 has been commented on: false
Issue #3847 has been updated: false
Closing issue because it was last updated on 2019-09-13T12:54:23Z
Closing issue #3847 - Just-In-Time code patching framework used in CS read barrier  for being stale
```

The configuration on our repository can be found here:
https://github.com/eclipse/omr/blob/6367999e3f811c226a48cfa03df267ef3e561d29/.github/workflows/stale.yml

```
        days-before-stale: 180
        days-before-close: 60
        exempt-issue-labels: 'backlog'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
```

The problem seems to be because eclipse/omr#3847 is older than 180 days, the action correctly marks it as stale on the following line:

https://github.com/actions/stale/blob/b6f9559915bf61a510aee92d2fdebec12bb9b335/src/IssueProcessor.ts#L166-L168

however it sets the `isStale` variable to `true` which then forces the logic on line 173 to run:
https://github.com/actions/stale/blob/b6f9559915bf61a510aee92d2fdebec12bb9b335/src/IssueProcessor.ts#L171-L174

Within this function we use `issue.updated_at` to determine whether the now stale issue should be closed:
https://github.com/actions/stale/blob/b6f9559915bf61a510aee92d2fdebec12bb9b335/src/IssueProcessor.ts#L204-L207

However this is **NOT** correct since the logic on line 166 has just marked the issue as stale, and the `issue.updated_at` was not changed accordingly, so we proceed to close the issue without waiting for `days-before-close` days to pass. This is a bug in my opinion, and to fix it we should be updating the `issue.updated_at` if we have just marked the issue with the stale label.

**Comment by fjeremic** [comment]
This regression seems to have been introduced in #64, and the test added there does not cover the issue at least `days-before-stale + days-before-close` days old. As part of the fix we should introduce another test for this use case. @hross FYI.

**Comment by hross** [comment]
Reopening this until I can tag the v3 release. Thanks for this update @fjeremic . I agree this seems like a sensible way to fix this.
