### ISSUE TITLE
Print current datetime and day difference while evaluating stale issues

### ISSUE THREAD

**Issue by asarkar** [actions/stale#846]
Using actions/stale@v6.

## The problem
```
[#49] Issue marked stale on: 2022-10-02T01:54:58Z
[#49] Checking for comments on issue since: 2022-10-02T01:54:58Z
[#49] Comments that are not the stale comment or another bot: 0
[#49] Issue has been commented on: false
[#49] Days before issue close: 7
[#49] The option remove-stale-when-updated (​https://github.com/actions/stale#remove-stale-when-updated​) is: true
[#49] The stale label should not be removed
[#49] Issue has been updated since it was marked stale: false
[#49] Issue has been updated in the last 7 days: true
[#49] Stale issue is not old enough to close yet (hasComments? false, hasUpdate? true)
  ```
  
The logs don't show the current datetime, so, for a human, it's difficult to understand the decision made to close/leave open.

## The solution

Show current datetime and day difference making it clear why an issue is closed/left open.

**Comment by asarkar** [comment]
Please consider update stale settings such that the OP doesn’t need to come here to say hi just to keep the ticket alive. It should be stale only if waiting for the OP, not if no one ever got to the ticket.

**Comment by Kisanja998** [comment]
Love spells, Marriage spells - Bring lost lover back
Stop lover from cheating, be in control of the love in the house. Fix your troubled marriage. Tried many try me last, 35 years of experience. Stop or make a Divorce. Fix a Broken Marriage. Fall in Love & Commitment. Stop cheating.
Love spells, Marriage spells - Bring lost lover back Stop lover from cheating, be in control of the love in the house. Fix your troubled marriage. Tried many try me last, 35 years of experience. Stop or make a Divorce. Stop cheating. Fall in Love & Commitment. Fix a Broken Marriage.
Contact Me
https://chiefaberash.com/
Get in Touch Get instant help for your love life now, with instant and guaranteed results.
Contact +27 63 5340727 Email info@chiefaberash.com

**Comment by dsame** [comment]
Hellow @asarkar ,  The message "Days before issue close: 7" makes clear the reason why the issue has been staled.

**Comment by dsame** [comment]
Hello @asarkar , i am closing the issue due to inactivity but pease feel free to reopen it or create a new one in case if problem still exists
