### ISSUE TITLE
Run action on more then one repository

### ISSUE THREAD

**Issue by omer-za** [actions/stale#849]
## The problem
I have a multiple repositories in our organizations that I want to apply this action on.
Today, I need to duplicate the actions to all repos, and have it running separately on each of them which also cause additional GitHub Actions minutes.

## The solution
Have this action contained in single repository and have an option to auto scan all repos / include / exclude specific repos.
Same as renovate bot has this option, see reference:
https://docs.renovatebot.com/self-hosted-configuration/#autodiscover

**Comment by glenn-jocher** [comment]
@omer-za did you ever find a solution for this?

**Comment by benoittgt** [comment]
I don't think this issue should be closed. Probot has the option `_extends`. https://github.com/probot/probot/blob/02d81f886cf8f4b7725523a1c4958127015dcfb0/docs/best-practices.md#store-configuration-in-the-repository

I will try this https://github.com/github/safe-settings and keep you updated.
