### ISSUE TITLE
Issue not being closed

### ISSUE THREAD

**Issue by fishcharlie** [actions/stale#91]
I have the following issue. It was marked as stale 8 days ago. But the stale bot never closed the issue.

https://github.com/dynamoose/dynamoose/issues/909

GitHub Action logs (https://github.com/dynamoose/dynamoose/runs/744186714?check_suite_focus=true):

```
Found issue: issue #909 - [BUG] can't define a schema which includes a list of objects in typescript last updated 2020-05-30T00:26:15Z (is pr? false)
59
Found a stale issue
60
Checking for label status:stale on issue #909
61
Issue #909 marked stale on: 2020-05-30T00:26:15Z
62
Checking for comments on issue #909 since 2020-05-30T00:26:15Z
63
Comments not made by fishcharlie or another bot: 0
64
Issue #909 has been commented on: false
65
Issue #909 has been updated: true
66
```

Any reason why this would be occurring?

**Comment by jwilner** [comment]
Looks maybe the same as #90

**Comment by hross** [comment]
@fishcharlie apologies for the inconvenience and introducing the regression. I have a fix up on this repo and submitted this PR https://github.com/dynamoose/dynamoose/pull/941 which should let you use the fix before I merge it into the master branch and publish a new version. I would love to get feedback on the behavior before I do so (that means you will have to switch it back assuming everything works as expected)

**Comment by hross** [comment]
Fixed an published in v3 tracking branch
