### ISSUE TITLE
Action doesn't fail on invalid credentials

### ISSUE THREAD

**Issue by neykov** [actions/stale#922]
**Description:**
Upon configuring the action with invalid credentials it reports a successful completion even though it wasn't able to connect.

```
Starting the stale action process...
Error: Get issues for repo error: Bad credentials
No more issues found to process. Exiting...
Statistics:
Operations performed: 1
```

**Action version:**
6.0.1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
* Configure the action as usual
* Provide invalid `repo-token`

**Expected behavior:**
The job should fail, along with the whole action execution.

**Actual behavior:**
The job successfully completes, even though it's not able to connect.

**Comment by dsame** [comment]
hello @neykov, thanks for your input. We started to investigate the issue

**Comment by dsame** [comment]
The https://github.com/actions/stale/pull/935 merged into the main and will be included it next release.

**Comment by panticmilos** [comment]
hi @neykov, we have released a new major [version](https://github.com/actions/stale/releases/tag/v8.0.0) that is addressing this issue.

Could you confirm it is working as expected?
