### ISSUE TITLE
Exampt pr/issue with owner

### ISSUE THREAD

**Issue by Eran-SSky** [actions/stale#930]
**Description:**
Hey!
it will be very helpful if the option to exampt stale PR's/issues according to the owner field.

**Justification:**
We don't use the assignee field for our PR's in the company so it will be very helpful to exampt users by the owner field instead of the assignee.

**Are you willing to submit a PR?**
Yes! 😄

**Comment by sgowroji** [comment]
@dsame, I think should be a must feature. Assignee would be very limited and hard to use those exempt. Could you please try providing this exempt-author or owner . Thanks!

**Comment by dsame** [comment]
duplicate of https://github.com/actions/stale/issues/933
