### ISSUE TITLE
Option to limit notifications per run

### ISSUE THREAD

**Issue by rcomer** [actions/stale#943]
**Description:**
Have a new option so that the action stops after it has made N actions (comment or close) that trigger a notification.  N should be configurable by the user.

**Justification:**
Over in [Matplotlib](https://github.com/matplotlib/matplotlib) we have _a lot_ of old issues to sift through, but we would also like to keep the number of notifications generated each day by the action fairly minimal.  Currently we have set the `operations-per-run` to a modest 30 to achieve the latter, but we know that, due to #792, we will need to keep increasing this to make more progress through the issue backlog.  With the proposed new option, we could set the `operations-per-run` to something high and notifications per run to something low, and thereby make slow but steady progress through our backlog.

**Are you willing to submit a PR?**
Potentially, but I have never done anything with actions or typescript, so I would need a lot of guidance.

**Comment by panticmilos** [comment]
hi @rcomer, thank you for the report. We will take a look at it :)

**Comment by rcomer** [comment]
The action has now started closing issues in Matplotlib.  It seems to be finding a pretty good equilibrium, in that closing issues frees up some operations for the next run (still a lot of old issues need labelling!)  So I do not think this feature would make so much difference for us now.

I’ll leave this open in case you think it would be useful for other projects, but also happy if you prefer to close.  Sorry for the noise.

**Comment by dsame** [comment]
Hello @rcomer , https://github.com/actions/stale/issues/792 already has a fix in the main branch, so will the problem be solved if the `operations-per-run` kept low?

**Comment by rcomer** [comment]
Hi @dsame, thanks for the ping.  I had not noticed that #792 was closed.  So if I've understood the change at #1033, the action will focus on finding new things to label as stale before it checks the ones already labelled.  I certainly think that makes this issue redundant.
