### ISSUE TITLE
Should scan starting with oldest PR rather than newest PR

### ISSUE THREAD

**Issue by msorens** [actions/stale#974]
**Description:**
When setting up this `stale` action in a workflow for the first time in a repo with a lot of PRs and a lot of them stale, the scan should start at the oldest one rather than the newest one. Or at least provide an option to do this. In one repo we have a lot of PRs that would meet the "stale" criteria—more than would be processed in a single run. So I and my coworkers were very surprised that the first run tagged the _newest_ batch of PRs.

**Action version:**
v8

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Have a repo with many dozens of stale PRs such that a single run of `stale` will only tag a portion of them.

**Expected behavior:**
The oldest PRs should be tagged by `stale`.

**Actual behavior:**
The newest PRs are tagged by `stale`.

**Comment by MAGICCC** [comment]
You can set `ascending: "true"` 
https://github.com/actions/stale#ascending

Can be argued that the maintainers of the action can change the default behavoir of ascending

**Comment by msorens** [comment]
Ah, I missed that option. Having it available is all I need. Thanks!

**Comment by marko-zivic-93** [comment]
Hello @msorens 
Thank you for your report and we are glad that you handled it all. If you experience any additional issues we are at your disposal.
